# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52b6218542fb4851214a0527f9a9ae3972cf127bfee55cb98eb909765e9187a66d938ff9841f504b3398b34e4c58cc66b6565829e2f66346b1cb0b087185da48

test:
  secret_key_base: 6909acf55bdc541c739971e4a67680b76f26f12d6629c3672eec63d76428d512ce4e4fd105159cd450200f3f9a6c82d993e366b3293bcc6c9a00aeda2e11ff60

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
